fhs/urls.py
from django.conf.urls import patterns, include, url
import views
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
        url(r'^$', views.index, name="index"),
        url(r'^register/$', views.register, name="register"),
        url(r'^login/$', views.user_login, name="login"),
        url(r'^logout/$', views.user_logout, name="logout"),
        url(r'^about/$', views.about, name="about"),
        url(r'^privacy-policy/$', views.privacy, name="privacy"),
        url(r'^terms-of-use/$', views.terms, name="terms"),
        url(r'^search/', views.search, name='search'),
        url(r'^save-page/', views.save_page, name='save_page'),
        url(r'^add_category/', views.add_category, name='add_category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/(?P<id>[0-9]+)/$', views.category, name='category'),
        url(r'^profile/(?P<user>[-\w.]+)/$', views.profile, name='profile'),
        url(r'^editprofile/', views.editprofile, name='editprofile'),
        url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
        url(r'^password-change/$', auth_views.password_change, {'template_name': 'fhs/changepassword.html'},name='userauth_password_change'),
        url(r'^password-change-done/$', auth_views.password_change_done, {'template_name': 'fhs/changepassworddone.html'}, name='password_change_done'),
        url(r'^goto/$', views.track_category, name='goto'),
        url(r'^delete-page/$', views.delete_page, name="delete_page"),
        url(r'^delete-category/$', views.delete_category, name="delete_category"),
        url(r'^update-category-state/$', views.update_category_state, name="update_category_state"),
        )

fhs_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import django.contrib.auth


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fhs_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^fhs/', include('fhs.urls')),
    url(r'^', include('fhs.urls')),

)

fhs/models.py
from django.db import models
from django.template.defaultfilters import slugify

from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    description = models.CharField(max_length=500, null=True)
    shared = models.BooleanField(default=False)
    slug = models.SlugField()
    views = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.id is None:
            if self.views < 0:
                self.views = 0
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    # def clean(self):
    #     self.name = self.name.capitalize()

    def __unicode__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=200)
    summary = models.TextField(default="No description provided")
    flesch_score = models.FloatField(default=0)
    sentiment_score = models.FloatField(default=0)
    subjectivity_score = models.FloatField(default=0)
    url = models.URLField(default="http://medlineplus.com")
    source = models.CharField(default="bing", max_length=30)

    def __unicode__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    age = models.IntegerField(default=20)
    gender = models.CharField(default="male", max_length=10)

    def __unicode__(self):
        return self.user.username

fhs/forms.py
from django import forms
from django.contrib.auth.models import User
from models import UserProfile, Page, Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'description', 'shared')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    age = forms.IntegerField(help_text="Enter your age")
    gender = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'age', 'gender')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture', 'age', 'gender')

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    summary = forms.CharField()
    category = forms.CharField()


    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        exclude = ('category', 'flesch_score', 'sentiment_score', 'subjectivity_score')


    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://') and not url.startswith('https://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data


class EmailForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']


class PasswordReset(forms.Form):
    oldpassword = forms.CharField(widget=forms.PasswordInput())
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordReset, self).__init__(*args, **kwargs)

    def clean_oldpassword(self):
        if self.clean_data.get('oldpassword') and not self.user.check_password(self.clean_data['oldpassword']):
            raise ValidationError('Please type your current password.')
        return self.clean_data['oldpassword']

    def clean_password2(self):
        if self.clean_data.get('password1') and self.clean_data.get('password2') and self.clean_data['password1'] != self.clean_data['password2']:
            raise ValidationError('The new passwords are not the same')
        return self.clean_data['password2']

fhs/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from forms import UserProfileForm, UserForm, CategoryForm, EmailForm
from models import Category, Page
from models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
import bing_search
import healthfinder_search, medlinePlus
from save_page_helper import *
from django.http import JsonResponse
import merge_by_relevance

from django.contrib.auth import views

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect


def delete_category(request):
    if request.is_ajax():
        category_id = request.POST['cat_id']
        try:
            theCategory=Category.objects.get(id = category_id)
            theCategory.delete()
            json_response={ "response": "Success"}
        except:
            json_response={"response": "Failure"}
    return JsonResponse(json_response)


def delete_page(request):
    if request.is_ajax():
        category_id = request.POST['cat_id']
        page_title = request.POST['page_title']
        try:
            theCategory = Category.objects.get(id=category_id)
            thePage = Page.objects.filter(title=page_title, category=theCategory)[0]
            thePage.delete()
            pages_count = len(Page.objects.filter(category=theCategory))
            json_response = {"response": "Success", 'pages_count':pages_count}
        except:
            json_response = {"response": "Failure"}
        return JsonResponse(json_response)


def track_category(request):
    cat_id = None
    url = '/fhs/'
    if request.method == 'GET':
        if 'cat_id' in request.GET:
            cat_id = request.GET['cat_id']
            try:
                category = Category.objects.get(id = cat_id)
                user = request.user
                if category.user != user:
                    category.views += 1
                    category.save()
                url = '/fhs/category/{}/{}/'.format(category.slug, cat_id)

            except:
                pass
    return redirect(url)


@login_required(login_url='/fhs/login/')
def add_category(request):

    if request.is_ajax():
        name = request.POST['name'].strip()
        description = request.POST['description']
        shared = request.POST['shared']

        if shared == "false":
            shared = False
        else:
            shared = True

        category = Category(user=request.user, name=name, description=description, shared=shared)

        # Saves it
        category.save()

        id = category.id

        category_url = Category.objects.get(id=id).slug

        return JsonResponse({"response":"Success", "category": category_url, "category_id": id })


    if request.method == "POST":
        category_data = request.POST
        category_data['name'] = category_data['name'].strip()
        if category_data['name'] == "":
            return render(request, "fhs/add_category.html", {"invalid": True})

        category_form = CategoryForm(data=category_data)
        if category_form.is_valid():
            try:
                category = category_form.save(commit=False)
                category.user = request.user
                category.save()

                return HttpResponseRedirect('/fhs/profile/'+request.user.username)
            except:
                return render(request, "fhs/add_category.html", {"existent": True})
        else:
            return render(request, "fhs/add_category.html", {"existent": True})

    return render(request, "fhs/add_category.html", {})


def category(request, category_name_slug, id):

    # Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug, id=id)
        context_dict['category_name'] = category.name

        # Retrieve all of the associated pages.
        # Note that filter returns >= 1 model instance.
        pages = Page.objects.filter(category=category)[::-1]

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category" message for us.
        pass

    # Go render the response and return it to the client.
    return render(request, 'fhs/category.html', context_dict)


def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/fhs/')


def index(request):

    if request.user.is_authenticated():
        public_categories = Category.objects.filter(shared=True)
    else:
        public_categories = Category.objects.filter(shared=True)[:5]

    return render(request, 'fhs/index.html', {'public_categories': public_categories})


def register(request):

    email_in_db = False
    registered = False
    username_taken = False
    name = None
    email = None
    age = None
    gender = None

    if request.method == 'POST':
        user_data = request.POST
        user_data['username'] = user_data['username'].strip()
        user_form = UserForm(data=user_data)
        profile_form = UserProfileForm(data=request.POST)
        name = user_data['username']
        email = user_data['email']
        age = user_data['age']

        gender = user_data['gender']


        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            # c heck if email is in the database
            email_to_be_checked = user.email
            # if no user has this email, the query will result in an error, then
            # the except statement will be executed, resulting in a successful registration
            try:
                test_user = User.objects.get(email=email_to_be_checked)
                email_in_db = True
            except User.DoesNotExist:
                # save user and user_profile, and sign in the user with the non-hashed password
                non_hashed_password = user.password
                user.set_password(non_hashed_password)
                user.save()
                profile = profile_form.save(commit=False)
                profile.user = user

                if 'picture' in request.FILES:
                    profile.picture = request.FILES['picture']
                profile.save()
                registered = True
                # In the end, log the user into the system
                theUser = authenticate(username=user.username, password=non_hashed_password)
                login(request, theUser)
        else:
            # convert the errors into a json format
            user_form_errors = json.loads(user_form.errors.as_json())
            # check if the user_form error was raised because someone tried to register with a username that is already in the dbs
            if user_form_errors.has_key("username") and \
                user_form_errors['username'][0]['message'] == "User with this Username already exists.":
                username_taken = True

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
            'fhs/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered,
             'email_in_db':email_in_db, 'username_taken':username_taken, "name": name, "email": email, "age": age, "gender": gender})


def user_login(request):
    name = None
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        name = username
        user = authenticate(username=username, password=password)

        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:

                login(request, user)
                return HttpResponseRedirect('/fhs/search/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your fhs account is disabled.")
        else:

            return render(request, 'fhs/login.html', {"invalid": True, "name": name})

    else:

        return render(request, 'fhs/login.html', {"name": name})


@login_required(login_url='/fhs/login/')
def search(request):

    results_from_bing = []
    results_from_healthgov = []
    results_from_medline = []
    context_dict = {}
    results_mashup = []
    categories = Category.objects.filter(user=request.user)
    public_categories = Category.objects.filter(shared=True)

    query = None
    age = None
    gender = "male"
    display = True

    if request.method == 'POST':
        checked_box = request.POST.get('search-target', None)
        query = request.POST['query'].strip()
        # search for me
        if checked_box == "on":
            age = UserProfile.objects.get(user = request.user).age
            gender = UserProfile.objects.get(user = request.user).gender
            display=True
        else:
            age = request.POST['age']
            gender = request.POST['gender']
            display=False

        if query and age and gender:

templates/fhs/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 public-cats">
                <h1>About the FHS Application</h1>
                <p class="lead">The Federated Health Search Application provides a secure and quick way for you to search for
                different conditions, medicines, symptoms and treatments.
                Users can search in the general web - Bing, and two specialised medical websites - Medline Plus and healthfinder.gov.<br/><br/>
                Registered users can create categories and save resources they find into them. Moreover, they can maintain their public profile
                and choose whether to share their categories with other users of the website.
                    The application should help the users understand if the information is easy to read,
                    is loaded with sentiment and subjectivity.
                Created by students at the University of Glasgow. For educational purposes only.
                <br/><br/>
                Andrey Georgiev, Georgi Koyrushki, Katya Bacheva, Veselin Vasilev.
                <br/>
                The Federated Health Search App © 2016
                <br/><br/>
                <a href="{% url 'index' %}">Go to home page</a>
                </p>

            </div>
        </div>
    </div>



{% endblock %}

templates/fhs/add_category.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Add Category{% endblock %}

{% block body_block %}
     <div class="container">
        <div class="row">
            <div class="register-formWrapper">
                <div class="col-xs-5 register-form ">
                    <form id="add_category" method="post" action="/fhs/add_category/" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h1>Create a category</h1>
                        {% if existent %}
                            <p class="reg-error" >A category with the specified name already exists.</p>
                        {% endif %}
                        {% if invalid %}
                            <p class="reg-error" >This is an invalid name for a category.</p>
                        {% endif %}
                        <div class="form-group">
                            <input class="register-input" id="id_name" maxlength="200" type="text" name="name" required autofocus value="" placeholder="Category name"/>
                        </div>
                        <div class="form-group">
                            <textarea class="register-input" id="id_description" maxlength="500" type="text" name="description"
                                   autofocus value="" placeholder="Provide a short description of this category"></textarea>
                        </div>
                        <div class="form-group">
                            <label id="cat-shared" for="id_shared">Do you want this to be a shared category?</label>
                            <input type="checkbox" name="shared">
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" name="submit" value="Add Category" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
     </div>

    <script src="{% static "js/category.js" %}"></script>
{% endblock %}

templates/fhs/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
        <li><a href="{% url 'goto' %}?cat_id={{ c.id }}">{{ c.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <strong>No public categories match your search.</strong>
{% endif %}

templates/fhs/changepassworddone.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Password change successful{% endblock %}

{% block body_block %}
    <div class="container">
        <div class="row">
            <div class="register-formWrapper">
                <div class="col-xs-5 register-form register-formWrapper">
                    <p>Your password has been changed successfully.</p>
                    <a href='/fhs/profile/{{ request.user.username }}'>Go back to your profile</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/fhs/index_cats.html
{% if cats %}
    <table class="table" valign="baseline">
    <tbody>
        {% for category in cats %}
            <tr>
            <td class="category-info">
                <p class="category-name"><strong>{{ category.name }}</strong></p>
            </td>
            <td>
                <span class="recipients-number"><strong>Shared by: </strong>{{ category.user }}</span>
            </td>
            <td class="category-sharer" valign="bottom" align="left">
                <p class="cat-descr"><strong>Description: </strong>{{ category.description }}</p>
            </td>
            <td class="text-right" valign="bottom">
                <a href="{% url 'goto' %}?cat_id={{ category.id }}"> See more</a>
            </td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
    {% else %}
        <strong>No public categories match your search.</strong>
{% endif %}

templates/fhs/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Register{% endblock %}

{% block body_block %}
    <div class="container">
        <div class="row">
            {% if registered %}
                <h1>Thank you for registering</h1>
                <p class="lead">The Federated Health Search Application provides a secure and quick way for you to search for
                different conditions, medicines, symptoms and treatments.
                Users can search in the general web - Bing, and two specialised medical websites - Medline Plus and healthfinder.gov.<br/><br/>
                Registered users can create categories and save resources they find into them. Moreover, they can maintain their public profile
                and choose whether to share their categories with other users of the website.
                The application should help the users understand if the information is easy to read,
                is loaded with sentiment and subjectivity.
                Created by students at the University of Glasgow. For educational purposes only.
                <br/><br/>
                Andrey Georgiev, Georgi Koyrushki, Katya Bacheva, Veselin Vasilev.
                <br/>
                The Federated Health Search App © 2016</p>
                <a href="{% url 'index' %}">Go to home page</a>
            {% else %}
                <div class="register-formWrapper">
                    <div class="col-xs-5 register-form register-formWrapper">

                        <form id="user_form" method="post" action="/fhs/register/"
                            enctype="multipart/form-data">
                            <h1>Register</h1>
                            {% csrf_token %}
                            {% if username_taken %}
                                <p class="reg-error" >Fail registration attempt: This username is already in the system. Please try again with a different username.</p>
                            {% endif %}
                            {% if name %}
                            <div class="form-group">
                                <input class="register-input" id="id_username" value="{{ name }}" required autofocus maxlength="50" name="username" placeholder="Account name" type="text">
                            </div>
                            {% else %}
                            <div class="form-group">
                                <input class="register-input" id="id_username" required autofocus maxlength="50" name="username" placeholder="Account name" type="text">
                            </div>
                            {% endif%}
                            {% if email_in_db %}
                                <p class="reg-error">Fail registration attempt: This email is already in the system. Please try again with a different email.</p>
                            {% endif %}

                            {% if email %}
                            <div class="form-group">
                                <input class="register-input" id="id_email" value="{{ email }}" maxlength="75" name="email" required placeholder="Email" type="email">
                            </div>
                            {% else %}
                            <div class="form-group">
                                <input class="register-input" id="id_email" maxlength="75" name="email" required placeholder="Email" type="email">
                            </div>
                            {% endif %}
                            <div class="form-group">
                                <input class="register-input" id="id_password" required name="password" maxlength="50" placeholder="Password" type="password">
                            </div>
                            {% if age %}
                            <div class="form-group">
                                <input class="register-input" id="id_age" value="{{ age }}" maxlength="3" name="age" required placeholder="Age" type="number" />
                            </div>
                            {% else %}
                            <div class="form-group">
                                <input class="register-input" id="id_age" maxlength="3" name="age" required placeholder="Age" type="number" />
                            </div>
                            {% endif %}
                            <div class="form-group">
                                <label for="gender-picker">Your gender</label>
                                <select id="gender-picker" name="gender" class="page-choice" required>
                                    {% if gender == "male" %}
                                        <option value="male" selected>Male</option>
                                        <option value="female">Female</option>
                                    {% else %}
                                        <option value="male">Male</option>
                                        <option value="female" selected>Female</option>
                                    {% endif %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label id="pic-label" for="uploadFile">Profile Picture</label>
                                <input id="uploadFile" placeholder="Choose File" disabled="disabled" />
                                <div class="fileUpload btn btn-default" id="uploadBtn">
                                    <span>Upload</span>
                                    <input id="uploadBtn" name="picture" type="file" class="upload" />
                                </div>
                            </div>
                            <div class="login"><input class="btn btn-primary sign-up-btn" type="submit" name="submit" value="Sign Up" /></div>
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    <script src="{% static "js/form_js.js" %}"></script>
{% endblock %}

templates/fhs/search_forms.html
<div class="list-group-item">
    <h4 class="list-group-item-heading"><a href="{{ result.url }}" target="_blank">{{ result.title }}</a></h4>
    <p class="list-group-item-text">{{ result.summary }}</p>
    <strong>Readibility: </strong> {{ result.flesh_score }} |
    <strong>Subjectivity: </strong> {{ result.subjectivity }} |
    <strong>Polarity: </strong> {{ result.polarity }}
    <form class="save_page_form" method="post" action="{% url 'save_page' %}">
        {% csrf_token %}
        <input type="hidden" class="hidden-info" value="{{ result.url }}" name="url"/>
        <input type="hidden" class="hidden-info" value="{{ result.title }}" name="title"/>
        <input type="hidden" class="hidden-info" value="{{ result.summary }}" name="summary"/>
        <input type="hidden" class="hidden-info" value="{{ result.source }}" name="source"/>
        <input type="hidden" class="hidden-info" value="{{ result.flesh_score }}" name="flesh_score"/>
        <input type="hidden" class="hidden-info" value="{{ result.subjectivity }}" name="subjectivity"/>
        <input type="hidden" class="hidden-info" value="{{ result.polarity }}" name="polarity"/>
        {% if categories %}
            <select name="category" class="category-choice" required>

                {% for category in categories %}
                    <option data-id="{{ category.id }}" value={{ category.name }}>{{ category.name }}</option>
                {% endfor %}
                    <option value="new-cat">Create a new category</option>
            </select>
            <input type="submit" class="btn btn-primary save-btn" value="Save page"/>
            <i class="fa fa-spinner faa-spin animated faa-slow"></i>
    </form>

        <div class="create-new-category-wrapper">
            <p class='create-new-category'>Create a category to save the page in.</p>
            <form class="add_category" method="post" action="/fhs/add_category/"
                                enctype="multipart/form-data">
                {% csrf_token %}
                 <input id="id_name" placeholder="Category name" class="new-cat-info" maxlength="200" name="name" type="text">
                    <input id="id_description" placeholder="Category description" class="new-cat-info"  maxlength="500" name="description" type="text">
                    Shared:
                    <input type="checkbox" id="id_shared" class="new-cat-info-btn" name="shared">
                    <input type="submit" class="btn btn-primary submit-new" name="submit-new" value="Create Category" />
                    <i class="fa fa-spinner faa-spin animated faa-slow"></i>
            </form>
        </div>
        {% else %}

            <select name="category" class="category-choice no-cats" required>
                <option value="new-cat">Create a new category</option>
            </select>
            <input type="submit" class="btn btn-primary save-btn" value="Save page"/>
            <i class="fa fa-spinner faa-spin animated faa-slow"></i>
        </form>
            <div class="create-new-category-wrapper">
                <p class='create-new-category'>Create a category to save the page in.</p>
                <form class="add_category" method="post" action="/fhs/add_category/"
                                    enctype="multipart/form-data">
                    {% csrf_token %}
                     <input id="id_name" placeholder="Category name" class="new-cat-info" maxlength="200" name="name" type="text">
                    <input id="id_description" placeholder="Category description" class="new-cat-info"  maxlength="500" name="description" type="text">
                    Shared:
                    <input type="checkbox" id="id_shared" class="new-cat-info-btn" name="shared">
                    <input type="submit" class="btn btn-primary submit-new" name="submit-new" value="Create Category" />
                    <i class="fa fa-spinner faa-spin animated faa-slow"></i>
                </form>
            </div>
        {% endif %}
    <!--</form>-->
</div>